superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('update/<int:hero_id>/', views.edit, name='edit'),
    path('delete/<int:hero_id>/', views.delete, name='delete')
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request,'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catchphrase = request.POST.get('catchphrase')
        my_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary_ability, secondary_ability=secondary_ability, catchphrase=catchphrase)
        my_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def delete(request, hero_id):
    current_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        current_hero.delete()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        context = {
        'current_hero': current_hero
        }
        return render(request, 'superheroes/delete.html', context)

def edit(request, hero_id):
    current_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        current_hero.name = request.POST.get('name')
        current_hero.alter_ego = request.POST.get('alter_ego')
        current_hero.primary_ability = request.POST.get('primary_ability')
        current_hero.secondary_ability = request.POST.get('secondary_ability')
        current_hero.catchphrase = request.POST.get('catchphrase')
        current_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        context = {
        'current_hero': current_hero
        }
        return render(request, 'superheroes/edit.html', context)

superhero_project/superheroes/templates/superheroes/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Super Duper Yah Yoobetcha{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/base.css' %}">
  </head>
<body>

<nav class="navbar sticky-top navbar-expand-lg navbar-dark">
        <a class="navbar-brand">Superhero Creator</a>
        {% block navbar%}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-item nav-link" href="{% url 'superheroes:create' %}">Build-a-Hero</a>
                  <a class="nav-item nav-link" href="{% url 'superheroes:index' %}">Home</a>
                </div>
              </div>
        {% endblock %}
</nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

superhero_project/superheroes/templates/superheroes/create.html
{% extends "superheroes/base.html" %}
{% block title %}Build-a-hero{% endblock %}
{% block content %}
<h1 class="header">Create a New Hero!</h1>

    <form action ="{% url 'superheroes:create' %}", method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name" id="name"/>
        </div>
        <div class="form-group">
            <label for="alter_ego">Alter Ego:</label>
            <input type="text" class="form-control" name="alter_ego" id="alter_ego"/>
        </div>
        <div class="form-group">
            <label for="primary_ability">Primary Ability:</label>
            <input type="text" class="form-control" name="primary_ability" id="primary_ability"/>
        </div>
        <div class="form-group">
            <label for="secondary_ability">Secondary Ability:</label>
            <input type="text" class="form-control" name="secondary_ability" id="secondary_ability"/>
        </div>
        <div class="form-group">
            <label for="catchphrase">Catchphrase:</label>
            <input type="text" class="form-control" name="catchphrase" id="catchphrase"/>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Create Hero</button>
    </form>
{% endblock %}

superhero_project/superheroes/templates/superheroes/delete.html
{% extends "superheroes/base.html "%}
{% block title %}d e l e t e{% endblock %}
{% block content %}
<h1>Are you sure you want to delete {{ current_hero.name }}?</h1>
    <form action ="{% url 'superheroes:delete' current_hero.id %}", method="POST">
        {% csrf_token %}
        <input type="submit" value="d e l e t e h e r o">
    </form>
{% endblock %}

superhero_project/superheroes/templates/superheroes/detail.html
{% extends "superheroes/base.html" %} 
{% block title %}Superhero Details{% endblock %}
{% block content %}
<h1 class="header">Details for {{single_hero.name}}</h1>
<h2>Also known as... {{single_hero.alter_ego}}</h2>
<h2>With the power of... {{single_hero.primary_ability}}</h2>
<h2>And also... {{single_hero.secondary_ability}}</h2>
<h2>And often heard shouting "{{single_hero.catchphrase}}!"</h2>
{% endblock %}

superhero_project/superheroes/templates/superheroes/edit.html
{% extends "superheroes/base.html" %}
{% block title %}Change-a-Hero{% endblock %}

{% block content %}
<h1 class="header">Update {{current_hero.name}}'s Information</h1>
<form action ="{% url 'superheroes:edit' current_hero.id %}", method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" name="name" class="form-control" id="name" value="{{ current_hero.name }}"/>
    </div>
    <div class="form-group">
        <label for="alter_ego">Alter Ego:</label>
        <input type="text" name="alter_ego" class="form-control" id="alter_ego" value="{{ current_hero.alter_ego }}"/>
    </div>
    <div class="form-group">
        <label for="primary_ability">Primary Ability:</label>
        <input type="text" name="primary_ability" class="form-control" id="primary_ability" value="{{ current_hero.primary_ability }}"/>
    </div>
    <div class="form-group">
        <label for="secondary_ability">Secondary Ability:</label>
        <input type="text" name="secondary_ability" class="form-control" id="secondary_ability" value="{{ current_hero.secondary_ability }}"/>
    </div>
    <div class="form-group">
        <label for="catchphrase">Catchphrase:</label>
        <input type="text" name="catchphrase" class="form-control" id="catchphrase" value="{{ current_hero.catchphrase }}"/>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Update Hero</button>
</form>
{% endblock %}

superhero_project/superheroes/templates/superheroes/index.html
{% extends "superheroes/base.html" %} {% block title %}Superhero Creator{%endblock %} {% block content %} {% load static %}
<h1 class="header">Welcome to the Superhero Creator!</h1>

<div class="row">
  <img src="{% static 'Axe-Cop.jpg' %}" class="img-fluid" alt="Axe Cop">
</div>
<h3 class="header">Your Current Superheroes:</h3>
<ul class="list-group">
  {% for hero in all_heroes %}
  <li class="list-group-item">
    <div>
      <h2>{{hero.name}}</h2>
    </div>
    <div>
      <h2>
        <a href="{% url 'superheroes:detail' hero.id %}">Details</a>
        <a href="{% url 'superheroes:edit' hero.id %}">Edit</a>
        <a href="{% url 'superheroes:delete' hero.id %}">Delete</a>
      </h2>
    </div>
  </li>
  {% endfor %}
</ul>

{% endblock %}